# Generated by Django 5.0.4 on 2024-04-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('ssn', models.IntegerField()),
            ],
        ),
    ]
