# Generated by Django 5.0.4 on 2024-04-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='Application',
        ),
    ]
